### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by GP3D84** [HelgeKeck/pam#25]
Hi, I'm unable to use pam after update, i've tried to reinstall but nothing change
I'm running RatOS v1.2.4-4-g898b8ae and PAM folder is empty after installation
[pam_install-output.txt](https://github.com/HelgeKeck/pam/files/10892928/pam_install-output.txt)

**Comment by HelgeKeck** [comment]
can you try to delete the 2 pam folders and then trying to fresh install it?

**Comment by GP3D84** [comment]
Hi, sorry for late reply, yes...
I try again now but the problem still here

**Comment by GP3D84** [comment]
@HelgeKeck this is the error on klipper.log when i add [include pam/ratos.cfg]
```
Unhandled exception during connect
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 175, in _connect
    self._read_config()
  File "/home/pi/klipper/klippy/klippy.py", line 141, in _read_config
    self.load_object(config, section_config.get_name(), None)
  File "/home/pi/klipper/klippy/klippy.py", line 130, in load_object
    self.objects[section] = init_func(config.getsection(section))
  File "/home/pi/klipper/klippy/extras/gcode_macro.py", line 191, in load_config_prefix
    return GCodeMacro(config)
  File "/home/pi/klipper/klippy/extras/gcode_macro.py", line 148, in __init__
    config.get(option))
  File "/usr/lib/python2.7/ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
webhooks client 3045310672: New connection
webhooks client 3045310672: Client info {'program': 'Moonraker', 'version': 'v0.8.0-23-g18f5ff4'}
```

**Comment by HelgeKeck** [comment]
just manually include one of the 3 includes you can find here in the repo
there are some issues with a system udpate

**Comment by HelgeKeck** [comment]
from here
https://github.com/HelgeKeck/pam/tree/main/klipper_macro

**Comment by GP3D84** [comment]
I've tried old version (December 2022) and no issue
When I'm at home i will try your advice and report
Thank you

**Comment by GP3D84** [comment]
i can't include because doesn't exits
i have this:
```
pi@ratos:~/klipper_config $ ls pam
klipper.cfg  pam.cfg  ratos.cfg
```
the same error for:
include pam/pam.cfg
include pam/ratos.cfg

**Comment by GP3D84** [comment]
No issue whit this: https://github.com/GP3D84/pam
Fell free to ask any test
Thanks you

**Comment by hersi97** [comment]
If you still have this issue, I debugged the klippy.py script and it seemed to come from `variable_prime_location` in the pam/<imported config>.cfg.
Simply changing line 17 from
`variable_prime_location: ""           # dynamicaly changed value, used by PAM for adaptive priming`
to
`variable_prime_location: ''           # dynamicaly changed value, used by PAM for adaptive priming`
fixed the startup error.

**Comment by heschlie** [comment]
Just to add some more noise, I ran into this today and noticed the symlink was pointed to the `ratos_v2.cfg` even though I am still on `v1.x` so I just swapped out the symlink and manually pointed it to the `ratos_v1.cfg` and it seems to be working well again.
